src/abilian/sbe/apps/notifications/__init__.py
# Copyright (c) 2012-2024, Abilian SAS

"""Notifications."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from abilian.app import Application

# Constants
TOKEN_SERIALIZER_NAME = "unsubscribe_sbe"  # noqa: S105


def register_plugin(app: Application) -> None:
    cfg = app.config.setdefault("ABILIAN_SBE", {})
    cfg.setdefault("DAILY_SOCIAL_DIGEST_SUBJECT", "Des nouvelles de vos communautés")

    # TODO: Slightly confusing. Reorg?
    # from .tasks.social import DEFAULT_DIGEST_SCHEDULE, DIGEST_TASK_NAME
    from .views import notifications, social

    # CELERYBEAT_SCHEDULE = app.config.setdefault("CELERYBEAT_SCHEDULE", {})
    # if DIGEST_TASK_NAME not in CELERYBEAT_SCHEDULE:
    #     CELERYBEAT_SCHEDULE[DIGEST_TASK_NAME] = DEFAULT_DIGEST_SCHEDULE

    app.register_blueprint(notifications)

src/abilian/sbe/apps/notifications/tasks/__init__.py
# Copyright (c) 2012-2024, Abilian SAS

src/abilian/sbe/apps/notifications/views/__init__.py
# Copyright (c) 2012-2024, Abilian SAS

from __future__ import annotations

from flask import Blueprint

notifications = Blueprint(
    "notifications",
    __name__,
    url_prefix="/notifications",
    template_folder="../templates",
)

src/abilian/sbe/apps/notifications/views/social.py
# Copyright (c) 2012-2024, Abilian SAS

"""First cut at a notification system."""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

from flask import request
from flask_login import current_user
from werkzeug.exceptions import MethodNotAllowed

from abilian.core.extensions import csrf, db
from abilian.core.models.subjects import User
from abilian.i18n import render_template_i18n
from abilian.sbe.apps.communities.security import require_admin
from abilian.sbe.apps.notifications import TOKEN_SERIALIZER_NAME
from abilian.sbe.apps.notifications.tasks.social import (
    make_message,
    send_daily_social_digest_to,
)
from abilian.services import get_service
from abilian.services.auth.views import get_token_status

from . import notifications

if TYPE_CHECKING:
    from abilian.services.preferences.service import PreferenceService

__all__ = ()

route = notifications.route


@require_admin
@route("/debug/social/")
def debug_social():
    """Send a digest to current user, or user with given email.

    Also displays the email in the browser as a result.
    """
    email = request.args.get("email")
    if email:
        user = User.query.filter(User.email == email).one()
    else:
        user = current_user

    msg = make_message(user)

    status = send_daily_social_digest_to(user)

    if status:
        return msg.html
    return "No message sent."


@route("/unsubscribe_sbe/<token>/", methods=["GET", "POST"])
@csrf.exempt
def unsubscribe_sbe(token: str) -> str:
    expired, invalid, user = get_token_status(token, TOKEN_SERIALIZER_NAME)
    if expired or invalid:
        return render_template_i18n("notifications/invalid-token.html")

    if request.method == "GET":
        return render_template_i18n(
            "notifications/confirm-unsubscribe.html", token=token
        )

    if request.method == "POST":
        preferences = cast("PreferenceService", get_service("preferences"))
        preferences.set_preferences(user, **{"sbe:notifications:daily": False})
        db.session.commit()
        return render_template_i18n("notifications/unsubscribed.html", token=token)
    raise MethodNotAllowed

src/abilian/sbe/apps/notifications/templates/notifications/_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>{# TODO #}</title>
  <style type="text/css">
    {% include "notifications/_style.css" %}
  </style>
</head>

<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0"
      offset="0">
<center>
  <table align="center" border="0" cellpadding="0" cellspacing="0"
         height="100%" width="100%" id="bodyTable">
    <tr>
      <td align="center" valign="top" id="bodyCell">
        <!-- BEGIN TEMPLATE // -->
        <table border="0" cellpadding="0" cellspacing="0"
               id="templateContainer">
          <tr>
            <td align="center" valign="top">
              <!-- BEGIN BODY // -->
              <table border="0" cellpadding="0" cellspacing="0" width="100%"
                     id="templateBody">
                <tr>
                  <td valign="top" class="bodyContent">
                    <h1>{% block title %}Your title goes here{% endblock %}</h1>

                    {% block body %}{% endblock %}
                  </td>
                </tr>
              </table>
              <!-- // END BODY -->
            </td>
          </tr>

          <tr>
            <td align="center" valign="top">
              <!-- BEGIN FOOTER // -->
              <table border="0" cellpadding="0" cellspacing="0" width="100%"
                     id="templateFooter">
                <tr>
                  <td valign="top" class="footerContent"
                      style="padding-bottom:20px;">
                    {% block footer %}{% endblock %}
                  </td>
                </tr>
              </table>
              <!-- // END FOOTER -->
            </td>
          </tr>
        </table>
        <!-- // END TEMPLATE -->
      </td>
    </tr>
  </table>
</center>
</body>
</html>

src/abilian/sbe/apps/notifications/templates/notifications/confirm-unsubscribe.fr.html
<html>
<body>

<h1>Veuillez confirmer votre demande de désabonnement des notifications</h1>

<p>
  Vous semblez vouloir vous désabonner des notifications quotidiennes des
  communautés.
</p>

<p>
  Pour confirmer cette décision, merci de bien vouloir cliquer sur le bouton
  ci-dessous:
</p>

<form action="." method="POST">
  <button>Me désabonner</button>
</form>

</body>
</html>

src/abilian/sbe/apps/notifications/templates/notifications/confirm-unsubscribe.html
<html>
<body>

<h1>Please confirm your request to unsubscribe from communities daily notifications</h1>

<p>
  After clicking the confirm button below, you will not receive another daily notification email.
</p>

<form action="." method="POST">
  <button>Confirm Unsubscribe</button>
</form>

</body>
</html>

src/abilian/sbe/apps/notifications/templates/notifications/daily-social-digest.fr.html
{% extends "notifications/_base.html" %}

{% block title %}
  Résumé quotidien des activités dans vos communautés
{% endblock %}

{% block body %}
  {% for digest in digests %}
    <h2>Dans la communauté: {{ digest.community.name }}</h2>

    {%- if digest.new_members %}
      <h3>Nouveaux membres</h3>

      {%- for user in digest.new_members %}
        <p>
          <a href="{{ url_for("social.user", user_id=user.id, _external=True,
                              _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ user }}</a>
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.new_documents %}
      <h3>Nouveaux documents</h3>

      {%- for doc in digest.new_documents %}
        <p><a href="{{ url_for("documents.document_view",community_id=digest.community.slug,
                               doc_id=doc.id, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ doc }}</a><br>
          <small>Posté par {{ doc.creator }}.</small>
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.updated_documents %}
      <h3>Documents mis à jour</h3>

      {%- for doc in digest.updated_documents %}
        <p><a href="{{ url_for("documents.document_view",
                               community_id=digest.community.slug,
                               doc_id=doc.id, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ doc }}</a>.
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.new_conversations %}
      <h3>Nouvelles conversations</h3>

      {%- for thread in digest.new_conversations %}
        <p><a href="{{ url_for("forum.thread",
                               community_id=digest.community.slug,
                               thread_id=thread.id, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ thread }}</a><br>
          <small>Posté par {{ thread.creator }}.</small>
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.updated_conversations %}
      <h3>Nouveaux commentaires dans les conversations</h3>

      {%- for thread, info in digest.updated_conversations.items() %}
        <p><a href="{{ url_for(info['post'], _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ thread }}</a><br>
          par {{ info['actors']|join(', ') }}
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.new_wiki_pages %}
      <h3>Nouvelles pages de wiki</h3>

      {%- for page in digest.new_wiki_pages %}
        <p><a href="{{ url_for('wiki.page',
                               community_id=digest.community.slug,
                               title=page.title, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ page }}</a><br>
          <small>par {{ page.creator }}.</small>
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.updated_wiki_pages %}
      <h3>Pages de wiki mises à jour</h3>


      {%- for page, actors in digest.updated_wiki_pages.items() %}
        <p><a href="{{ url_for('wiki.page',
                               community_id=digest.community.slug,
                               title=page.title, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ page }}</a>
          <br>
          <small>par
            {% for actor, changes in actors.items() %}{{ actor }}
              {%- if changes > 1 %} (x{{ changes }}){% endif %}
              {%- if not loop.last %}, {% endif -%}
            {%- endfor %}.
          </small>
        </p>
      {%- endfor %}
    {%- endif %}

  {% endfor %}
{% endblock %}

{% block footer %}
  Vous recevez ce mail car vous êtes abonné aux notifications de
  vos communautés.
  <br>
  Vous pouvez modifier les notifications que vous recevez en
  allant sur la page
  <a href="{{ url_for("preferences.index", _external=True, _scheme=config['PREFERRED_URL_SCHEME']) }}">Préférences</a>
  de l'application.
  <br>
  Vous pouvez également vous désabonner directement en suivant
  <a href="{{ url_for("notifications.unsubscribe_sbe", token=token, _external=True, _scheme=config['PREFERRED_URL_SCHEME']) }}">ce
    lien</a>.
{% endblock %}

src/abilian/sbe/apps/notifications/templates/notifications/daily-social-digest.html
{% extends "notifications/_base.html" %}

{% block title %}
  Daily summary of activities in your communities
{% endblock %}

{% block body %}
  {% for digest in digests %}
    <h2>In the {{ digest.community.name }} community</h2>

    {%- if digest.new_members %}
      <h3>New members</h3>

      {%- for user in digest.new_members %}
        <p>
          <a href="{{ url_for("social.user", user_id=user.id, _external=True,
                              _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ user }}</a>
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.new_documents %}
      <h3>New documents</h3>

      {%- for doc in digest.new_documents %}
        <p><a href="{{ url_for("documents.document_view",
                               community_id=digest.community.slug,
                               doc_id=doc.id, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ doc }}</a><br>
          <small>Posted by {{ doc.creator }}.</small>
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.updated_documents %}
      <h3>Updated documents</h3>

      {%- for doc in digest.updated_documents %}
        <p><a href="{{ url_for("documents.document_view",
                               community_id=digest.community.slug,
                               doc_id=doc.id, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ doc }}</a>.
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.new_conversations %}
      <h3>New conversations</h3>

      {%- for thread in digest.new_conversations %}
        <p><a href="{{ url_for("forum.thread",
                               community_id=digest.community.slug,
                               thread_id=thread.id, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ thread }}</a><br>
          <small>Posted by {{ thread.creator }}.</small>
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.updated_conversations %}
      <h3>New comments in conversations</h3>

      {%- for thread, info in digest.updated_conversations.items() %}
        <p><a href="{{ url_for(info['post'], _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ thread }}</a><br>
          by {{ info['actors']|join(', ') }}
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.new_wiki_pages %}
      <h3>New wiki pages</h3>

      {%- for page in digest.new_wiki_pages %}
        <p><a href="{{ url_for('wiki.page',
                               community_id=digest.community.slug,
                               title=page.title, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ page }}</a>
          <br>
          <small>Posted by {{ page.creator }}.</small>
        </p>
      {%- endfor %}
    {%- endif %}

    {%- if digest.updated_wiki_pages %}
      <h3>Updated wiki pages</h3>

      {%- for page, actors in digest.updated_wiki_pages.items() %}
        <p><a href="{{ url_for('wiki.page',
                               community_id=digest.community.slug,
                               title=page.title, _external=True,
                               _scheme=config['PREFERRED_URL_SCHEME']) }}">{{ page }}</a><br>
          <small>by
            {% for actor, changes in actors.items() %}{{ actor }}
              {% if changes > 1 %}(x{{ changes }}){% endif %}
              {%- if not loop.last %}, {% endif %}
            {%- endfor %}.
          </small>

          {{ actors }}

        </p>
      {%- endfor %}
    {%- endif %}
  {% endfor %}
{% endblock %}

{% block footer %}
  You receive this email because you are subscribed to communities notifications.
  <br>
  You can modify your notifications by going to the application's
  <a href="{{ url_for("preferences.index", _external=True, _scheme=config['PREFERRED_URL_SCHEME']) }}">Preferences</a>
  page.
  <br>
  You can unsubscribe by following
  <a href="{{ url_for("notifications.unsubscribe_sbe", token=token, _external=True, _scheme=config['PREFERRED_URL_SCHEME']) }}">this
    link</a>.
{% endblock %}

src/abilian/sbe/apps/notifications/templates/notifications/invalid-token.fr.html
<html>
<body>

<h1>Jeton d'authentification invalide. </h1>

<p>
  Nous sommes désolés, mais votre jeton d'authentification est invalide ou
  expirés.
</p>

<p>
  Vous pouvez vous désabonner des notifications en vous <a href="/login/">
  connectant puis en allant dans le menu "Préférences" en haut à droite de
  l'écran.</a>
</p>

</body>
</html>

src/abilian/sbe/apps/notifications/templates/notifications/invalid-token.html
<html>
<body>

<h1>
  Invalid authentication token. </h1>

<p>
  We're sorry but you authentication token is invalid or expired.
</p>

<p>
  You can unsubscribe from notifications by login in <a href="/login/">
  and going to the "Preferences" menu in the top right corner of the screen.</a>
</p>

</body>
</html>

src/abilian/sbe/apps/notifications/templates/notifications/unsubscribed.fr.html
<html>
<body>

<h1>Vous avez été désabonné(e) des notifications des communautés</h1>

<p>
  Désolés si ces mails vous ont importuné.
</p>


</body>
</html>

src/abilian/sbe/apps/notifications/templates/notifications/unsubscribed.html
<html>
<body>

<h1>You have unsubscribed from communities notifications</h1>

<p>
  Sorry if those mails annoyed you. </p>

</body>
</html>