src/abilian/sbe/apps/social/views/groups.py
# Copyright (c) 2012-2024, Abilian SAS

from __future__ import annotations

from pathlib import Path

from flask import (
    current_app,
    flash,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_babel import gettext as _
from flask_login import current_user
from sqlalchemy import func
from werkzeug.exceptions import InternalServerError, NotFound

from abilian.core.extensions import db
from abilian.core.models.subjects import Group, User
from abilian.services import get_service
from abilian.services.image import CROP, resize
from abilian.services.security import security
from abilian.web import csrf
from abilian.web.views import default_view

from .social import social

DEFAULT_GROUP_MUGSHOT = (
    (Path(__file__).parent / ".." / ".." / ".." / "static" / "images" / "frog.jpg")
    .open("rb")
    .read()
)


@social.route("/groups/")
def groups() -> str:
    tab = request.args.get("tab", "all_groups")
    if tab == "all_groups":
        groups = Group.query.order_by(Group.name).all()
        if not security.has_role(current_user, "admin"):
            groups = [
                group
                for group in groups
                if group.public or current_user in group.members
            ]
    else:
        groups = current_user.groups
        groups.sort(key=lambda x: x.name)

    return render_template("social/groups.html", groups=groups)


def is_admin(group):
    security = get_service("security")
    is_admin = current_user in group.admins
    if not is_admin and "security" in current_app.extensions:
        is_admin = security.has_role(current_user, "admin")

    return is_admin


@social.route("/groups/<int:group_id>")
@default_view(social, Group, "group_id")
def group_home(group_id):
    group = Group.query.get(group_id)
    ctx = {"group": group, "is_admin": is_admin(group)}
    return render_template("social/group.html", **ctx)


@social.route("/groups/<int:group_id>/json")
def group_json(group_id):
    members = Group.query.get(group_id).members
    q = request.args.get("q", "").lower()
    if q:
        members = [
            u
            for u in members
            if any(
                term.startswith(q)
                for name in (u.first_name.lower(), u.last_name.lower())
                for term in name.split()
            )
        ]

    result = {"results": [{"id": obj.id, "text": obj.name} for obj in members]}
    return jsonify(result)


@social.route("/groups/<int:group_id>", methods=["POST"])
@csrf.protect
def group_post(group_id):
    group = Group.query.get(group_id)
    action = request.form.get("action")
    return_url = request.form.get("return_url")
    user_id = request.form.get("user", "").strip()

    membership_actions = frozenset(("add", "remove", "add-admin", "remove-admin"))

    if action not in {"join", "leave"} | membership_actions:
        msg = f"Unknown action: {action}"
        raise ValueError(msg)

    if action not in ("join", "leave"):
        assert is_admin(group)

    if action == "join":
        current_user.join(group)
    elif action == "leave":
        current_user.leave(group)

    elif action in membership_actions:
        try:
            user_id = int(user_id)
        except ValueError:
            flash(_("Error: No user selected"), "error")
            return redirect(url_for(".group_home", group_id=group_id))

        user = User.query.get(user_id)

        if action == "add":
            user.join(group)
        elif action == "remove":
            user.leave(group)
        elif action == "add-admin":
            if user not in group.admins:
                group.admins.append(user)
        elif action == "remove-admin":
            if user in group.admins:
                group.admins.remove(user)

    db.session.commit()

    if not return_url:
        return_url = url_for(".group_home", group_id=group_id)

    # TODO: security check
    return redirect(return_url)


@social.route("/groups/new")
def groups_new() -> None:
    # TODO later
    return

    # e = Env()
    # e.form = GroupForm()
    # return render_template("social/groups-new.html", **e)


@social.route("/groups/new", methods=["POST"])
def groups_new_post() -> None:
    # TODO later
    return

    # form = GroupForm()
    #
    # if form.validate():
    #     group = Group()
    #     form.populate_obj(group)
    #     db.session.add(group)
    #     db.session.commit()
    #     flash(_(u"Your new group has been created"), category='info')
    #     return redirect(url_for('.group_home', group_id=group.id))
    #
    # else:
    #     e = Env()
    #     e.form = form
    #     return render_template("social/groups-new.html", **e)


@social.route("/groups/<int:group_id>/mugshot")
def group_mugshot(group_id):
    # TODO: duplicated code (with user_mugshot). Extract common method.
    size = int(request.args.get("s", 55))
    if size > 500:
        msg = f"Error, size = {size:d}"
        raise ValueError(msg)
    group = Group.query.get(group_id)

    if not group:
        raise NotFound

    if group.photo:
        data = group.photo
    else:
        data = DEFAULT_GROUP_MUGSHOT

    if size:
        data = resize(data, size, size, mode=CROP)

    response = make_response(data)
    response.headers["content-type"] = "image/jpeg"
    response.headers.add("Cache-Control", "public, max-age=600")
    return response


#
# Ad-hoc JSON endpoints, used by select boxes
#
@social.route("/groups/json")
def groups_json():
    q = request.args.get("q").replace("%", " ").lower()

    if not q or len(q) < 2:
        raise InternalServerError

    query = Group.query
    # query = query.filter(func.lower(Group.name).like(q + "%"))
    query = query.order_by(func.lower(Group.name))
    all = query.all()

    result = {"results": [{"id": obj.id, "text": obj.name} for obj in all]}
    return jsonify(result)

src/abilian/sbe/apps/social/views/social.py
# Copyright (c) 2012-2024, Abilian SAS

"""The blueprint for this app."""

from __future__ import annotations

from flask import Blueprint, redirect, render_template, url_for

from abilian.core.extensions import db
from abilian.core.util import get_params
from abilian.sbe.apps.social.models import Message
from abilian.sbe.apps.wall.presenters import ActivityEntryPresenter
from abilian.sbe.apps.wall.util import get_recent_entries

__all__ = ["social"]

MAX_LAST_USERS = 15
MAX_MESSAGES = 15

social = Blueprint(
    "social", __name__, url_prefix="/social", template_folder="../templates"
)
route = social.route


@route("/")
def home() -> str:
    ctx = {}
    entries = get_recent_entries(num=50)
    entries = ActivityEntryPresenter.wrap_collection(entries)
    ctx["activity_entries"] = entries

    return render_template("social/home.html", **ctx)


@route("/stream/<stream_name>")
def stream(stream_name) -> None:
    pass


@route("/", methods=["POST"])
def share():
    # TODO: better error control / feedback
    d = get_params(Message.__editable__)
    if not d.get("content"):
        return redirect(url_for(".home"))

    message = Message(**d)
    db.session.add(message)

    # tags = message.tags
    # values = [ {'tag': tag, 'message_id': message.id} for tag in tags ]
    # db.engine.execute(tagging.insert(), values)

    db.session.commit()
    return redirect(url_for(".home"))

src/abilian/sbe/apps/social/views/users.py
# Copyright (c) 2012-2024, Abilian SAS

from __future__ import annotations

import pkgutil
from html import escape

import sqlalchemy as sa
import sqlalchemy.exc
import sqlalchemy.orm
from flask import Response, flash, jsonify, redirect, render_template, request
from flask_login import current_user
from loguru import logger
from sqlalchemy.sql.expression import and_, asc, desc, func, nullslast, or_
from werkzeug.exceptions import InternalServerError

from abilian.core.extensions import db
from abilian.core.models.subjects import User
from abilian.i18n import _, _l
from abilian.sbe.apps.communities.models import Membership
from abilian.sbe.apps.social.forms import UserProfileForm, UserProfileViewForm
from abilian.sbe.apps.wall.presenters import ActivityEntryPresenter
from abilian.sbe.apps.wall.views import get_recent_entries
from abilian.services import security_service
from abilian.web import url_for
from abilian.web.filters import age
from abilian.web.views import ObjectEdit, default_view
from abilian.web.views.images import user_photo_url

from .social import social

DEFAULT_USER_MUGSHOT = pkgutil.get_data(
    "abilian.sbe", "static/images/silhouette_unknown.png"
)


def make_tabs(user: User) -> list[dict[str, str]]:
    return [
        {"id": "profile", "label": _("Profile"), "link": url_for(user, tab="profile")},
        # dict(id='conversations', label=_(u'Conversations'), link=url_for(user), is_online=True),
        {
            "id": "documents",
            "label": _("Documents"),
            "link": url_for(user, tab="documents"),
        },
        {"id": "images", "label": _("Images"), "link": url_for(user, tab="images")},
        {"id": "audit", "label": _("Audit"), "link": url_for(user, tab="audit")},
    ]


@social.route("/users/")
def users() -> str:
    query = request.args.get("query")

    if query:
        query = query.replace("%", " ")
        q = or_(
            User.first_name.like(f"%{query}%"),
            User.last_name.like(f"%{query}%"),
        )
        users = User.query.filter(q).limit(100).all()
    else:
        users = User.query.limit(100).all()
    ctx = {"users": users}
    return render_template("social/users.html", **ctx)


@social.route("/users/dt_json")
def users_dt_json():
    """JSON call to fill a DataTable.

    Needs some refactoring.
    """
    args = request.args

    length = int(args.get("iDisplayLength", 0))
    start = int(args.get("iDisplayStart", 0))
    sort_col = int(args.get("iSortCol_0", 1))
    sort_dir = args.get("sSortDir_0", "asc")
    echo = int(args.get("sEcho", 0))
    search = args.get("sSearch", "").replace("%", "").lower()

    end = start + length

    query = User.query
    total_count = query.count()

    if search:
        # TODO: gérer les accents
        filter = or_(
            func.lower(User.first_name).like(f"%{search}%"),
            func.lower(User.last_name).like(f"%{search}%"),
        )
        query = query.filter(filter).reset_joinpoint()

    count = query.count()
    SORT_COLS = {
        1: [],  # will be set to [User.last_name, User.first_name]
        2: [User.created_at],
        3: [User.last_active],
    }
    columns = list(SORT_COLS.get(sort_col, []))
    columns.extend([func.lower(User.last_name), func.lower(User.first_name)])

    direction = asc if sort_dir == "asc" else desc
    order_by = [direction(column) for column in columns]

    # sqlite does not support 'NULLS FIRST|LAST' in ORDER BY clauses
    engine = query.session.get_bind(User.__mapper__)
    if engine.name != "sqlite":
        order_by[0] = nullslast(order_by[0])

    query = query.order_by(*order_by)

    users = query.slice(start, end).all()

    data = []
    MUGSHOT_SIZE = 45
    for user in users:
        # TODO: this should be done on the browser.
        user_url = url_for(".user", user_id=user.id)
        mugshot = user_photo_url(user, size=MUGSHOT_SIZE)
        name = escape(user.name or "")

        cell0 = (
            f'<a href="{user_url}"><img src="{mugshot}" width="{MUGSHOT_SIZE}" height="{MUGSHOT_SIZE}">'
            "</a>"
        )
        cell1 = f'<div class="info"><a href="{user_url}">{name}</a></div>'
        cell2 = age(user.created_at)
        cell3 = age(user.last_active)
        _cell4 = ""  # TODO: follow / unfollow?

        data.append([cell0, cell1, cell2, cell3])

    result = {
        "sEcho": echo,
        "iTotalRecords": total_count,
        "iTotalDisplayRecords": count,
        "aaData": data,
    }
    return jsonify(result)


@social.route("/users/<int:user_id>")
@default_view(social, User, "user_id")
def user(user_id: int) -> str:
    user = User.query.get(user_id)

    # FIXME: use user profiles
    view_form = UserProfileViewForm(obj=user)

    communities = [m.community for m in user.communautes_membership]
    if current_user != user and (
        not security_service.has_role(current_user, "manager")
    ):
        # filter visible communautes (ticket 165)
        communities = [c for c in communities if c.has_member(current_user)]

    view_form.communautes._set_data(communities)

    # FIXME
    contact = user
    entries = get_recent_entries(user=user)
    entries = ActivityEntryPresenter.wrap_collection(entries)
    ctx = {
        "user": user,
        "contact": contact,
        "view_form": view_form,
        "can_edit": can_edit(user),
        "tabs": make_tabs(user),
        "activity_entries": entries,
    }
    return render_template("social/user.html", **ctx)


def can_edit(user: User) -> bool:
    # TODO: introduce a "self" role?
    return (user == current_user) or security_service.has_role(current_user, "admin")


class UserProfileEdit(ObjectEdit):
    Model = User
    Form = UserProfileForm
    pk = "user_id"
    _message_success = _l("Profile edited")

    def init_object(self, args, kwargs):
        args, kwargs = super().init_object(args, kwargs)
        self.user = self.obj
        return args, kwargs

    def view_url(self):
        return url_for(".user", user_id=self.user.id)

    def edit(self):
        if not can_edit(self.user):
            return Response(status=403)
        return super().edit()

    def handle_commit_exception(self, exc):
        db.session.rollback()
        if isinstance(exc, sa.exc.IntegrityError):
            log_msg = "Error saving user profile"
        else:
            log_msg = "Unexpected error while saving user profile"
        logger.opt(exception=True).error(log_msg, extra={"stack": True})
        flash(_("Error occured"), "error")
        return self.redirect_to_view()


social.route("/users/<int:user_id>/edit")(UserProfileEdit.as_view("user_edit"))


@social.route("/users/<int:user_id>", methods=["POST"])
def user_post(user_id):
    user = User.query.get(user_id)
    action = request.form.get("action")
    return_url = request.form.get("return_url")

    if action == "follow":
        current_user.follow(user)
    elif action == "unfollow":
        current_user.unfollow(user)
    else:
        msg = "Should not happen"
        raise Exception(msg)
    db.session.commit()

    if return_url:
        # TODO: security check
        return redirect(return_url)
    return redirect(url_for(".user_view", user_id=user_id))


#
# Ad-hoc JSON endpoints, used by select boxes
#
@social.route("/users/json")
def users_json():
    q = request.args.get("q").replace("%", " ").lower()

    if not q or len(q) < 2:
        raise InternalServerError

    query = User.query.filter(
        or_(
            func.lower(User.first_name).like(f"{q}%"),
            func.lower(User.last_name).like(f"{q}%"),
        )
    ).order_by(func.lower(User.last_name))

    with_membership = request.args.get("with_membership")
    if with_membership is not None:
        # provide membership info for a community
        with_membership = int(with_membership)
        query = (
            query.outerjoin(
                Membership,
                and_(
                    Membership.user.expression,
                    Membership.community_id == with_membership,
                ),
            )
            .filter(User.can_login == True)
            .add_columns(Membership.role)
        )

    exclude_community = request.args.get("exclude_community")
    if exclude_community is not None:
        exclude_community = int(exclude_community)
        exclude = (
            ~Membership.query.filter(
                Membership.user.expression, Membership.community_id == exclude_community
            )
            .options(sa.orm.noload("user"), sa.orm.noload("community"))
            .exists()
        )
        query = query.filter(exclude)

    results = []
    for user in query.all():
        role = None
        if with_membership is not None:
            user, role = user

        if role is not None:
            role = str(role)

        item = {
            "id": user.id,
            "text": f"{user.name} ({user.email})",
            "name": user.name,
            "email": user.email,
            "role": role,
        }
        results.append(item)

    return jsonify({"results": results})

src/abilian/sbe/apps/social/templates/social/_sidebar.html
{% from "macros/box.html" import m_box, m_box_menu with context %}

{% call m_box_menu() %}
  <ul class="nav nav-list">
  <ul class="nav nav-list">
    <li><a href="{{ url_for("social.home") }}">{{ _("My feed") }}</a></li>
    <li><a href="{{ url_for(current_user) }}">{{ _("My profile") }}</a></li>
    <li><a href="{{ url_for("social.users") }}">{{ _("User directory") }}</a></li>
  </ul>
{% endcall %}


{% call m_box(_("My communities"), color="orange") %}
  <ul class="nav nav-list">
    {% set communities = g.sidebars.my_communities %}
    {% for community in communities %}
      <li><a
          href="{{ url_for("communities.community", community_id=community.slug) }}">{{ community.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endcall %}


{% call m_box(_("Latest visitors"), color="orange") %}
  <ul class="latest-visitors">
    {%- set img_online = url_for('abilian_sbe_static', filename='img/greendot.png') %}
    {%- for user in g.sidebars.latest_visitors %}
      <li><a href="{{ url_for(user) }}">
        <img class="avatar" src="{{ user_photo_url(user, size=20) }}" alt=""/>
        {{ user.name }}
      </a>
        {%- if user.is_online %}
          <img src="{{ img_online }}" alt=""/>
        {%- endif %}
      </li>
    {%- endfor %}
  </ul>
{%- endcall %}

src/abilian/sbe/apps/social/templates/social/base.html
{% extends "base.html" %}

{% from "macros/box.html" import m_box, m_box_menu with context %}

{% block main %}
  <div class="row">
    <div class="col-md-9">
      {% block content %}
      {% endblock %}
    </div>

    <div class="col-md-3">
      {% block sidebar %}
        {% include "social/_sidebar.html" %}

        {#        {% call m_box_menu() %}#}
        {#          <ul class="nav nav-list">#}
        {#            <li><a href="{{ url_for("social.home") }}">{{ _("My feed") }}</a></li>#}
        {#            <li><a href="{{ url_for(g.user) }}">{{ _("My profile") }}</a></li>#}
        {#            <li><a href="{{ url_for(".users") }}">{{ _("User directory") }}</a></li>#}
        {#          </ul>#}
        {#        {% endcall %}#}
        {##}
        {#        {% call m_box(_("Latest visitors"), color="orange") %}#}
        {#          <ul class="latest-visitors">#}
        {#            {%- set img_online = url_for('abilian_sbe_static', filename='img/greendot.png') %}#}
        {#            {%- for user in g.sidebars.latest_visitors %}#}
        {#              <li><a href="{{ url_for(user) }}">#}
        {#                <img class="avatar" src="{{ user_photo_url(user, size=20) }}" alt="" />#}
        {#                {{ user.name }}#}
        {#              </a>#}
        {#              {%- if user.is_online %}#}
        {#                <img src="{{ img_online }}" alt="" />#}
        {#              {%- endif %}#}
        {#              </li>#}
        {#            {%- endfor %}#}
        {#          </ul>#}
        {#        {%- endcall %}#}

      {%- endblock %}
    </div>
  </div>
{%- endblock %}

src/abilian/sbe/apps/social/templates/social/group.html
{% extends "social/base.html" %}

{% macro m_user_list(users, form_action, form_action_label) %}
  {%- if users %}
    {%- if is_admin %}
      <form action="{{ url_for('.group_post', group_id=group.id) }}" method="POST">
      {{ csrf.field() }}
      <input type="hidden" name="action" value="{{ form_action }}"/>
    {%- endif %}
  <table class="table table-striped table-condensed">
    <tbody>
    {%- for user in users %}
      <tr>
        <td>
          <a href="{{ url_for(user) }}">
            <img src="{{ user_photo_url(user, size=16) }}" alt="{{ user.name }}" title="{{ user.name }}"
                 style="margin-bottom: 4px;"/>
            {{ user.name }}
          </a>
        </td>
        <td>{{ user.email }}</td>
        {%- if is_admin %}
          <td>
            <button class="btn btn-danger" name="user" value="{{ user.id }}" title="{{ form_action_label }}"><i
                class="fa fa-ban"></i></button>
          </td>
        {%- endif %}
      </tr>
    {%- endfor %}
    </tbody>
  </table>
  {%- if is_admin %}
    </form>
  {%- endif %}
  {%- endif %}
{% endmacro %}

{% block content %}
  <div class="header">
    <img src="{{ url_for(".group_mugshot", group_id=group.id, s=140) }}" class="avatar avatar-140" alt=""/>

    <div class="info">
      <h2 class="title">{{ group.name }}</h2>

      <div class="job-title">{{ group.description or '' }}</div>
      {#
      <form action="." method="post" style="margin-top: 10px;">
        {{ csrf.field() }}
        {% if g.user.is_member_of(group) %}
          <button class="btn" name="action" value="leave">{{ _("Leave") }}</button>
        {% else %}
          <button class="btn" name="action" value="join">{{ _("Join") }}</button>
        {% endif %}
      </form>
      #}
    </div>

    <ul class="nav nav-tabs clear">
      {%- for tab in tabs %}
        {%- if tab.id == active_tab_id %}
          <li class="active"><a href="{{ tab.link }}">{{ _(tab.label) }}</a></li>
        {%- else %}
          <li><a href="{{ tab.link }}">{{ _(tab.label) }}</a></li>
        {%- endif %}
      {%- endfor %}
    </ul>

  </div>

  {#
  {% if g.is_manager or g.user.is_admin_of(group) %}
    admin...
  {% endif %}
  #}
  <h3>{{ _("Group admins") }}</h3>
  {%- if is_admin %}
    <form action="{{ url_for('.group_post', group_id=group.id) }}" method="POST">
      {{ csrf.field() }}
      <input type="text" id="admin-select" name="user"/>
      <button type="submit" class="btn" name="action" value="add-admin"><i class="fa fa-plus"></i></button>
    </form>
  {%- endif %}

  {{ m_user_list(group.admins, 'remove-admin', _('remove from administrators')) }}

  <h3>{{ _("Group members") }}</h3>

  {%- if is_admin %}
    <form action="{{ url_for('.group_post', group_id=group.id) }}" method="POST">
      {{ csrf.field() }}
      <input type="text" id="user-select" name="user"/>
      <button type="submit" class="btn" name="action" value="add"><i class="fa fa-plus"></i></button>
    </form>
  {%- endif %}
  {{ m_user_list(group.members, 'remove', _('remove from group')) }}

{% endblock %}

{% block js %}
  <script>
    $(document).ready(function () {
      $("#user-select").attr("style", "width: 220px").select2({
        minimumInputLength: 2,
        ajax: {
          url: "{{ url_for("social.users_json") }}",
          dataType: 'json',
          quietMillis: 100,
          data: function (term, page) {
            return {q: term};
          },
          results: function (data, page) {
            return {results: data.results, more: false};
          }
        },
        allowClear: true
      });
      $("#s2id_user-select a span").text("");
      $("input#user-select").attr("value", "");

      $("#admin-select").attr("style", "width: 220px").select2({
        minimumInputLength: 2,
        ajax: {
          url: "{{ url_for(".group_json", group_id=group.id) }}",
          dataType: 'json',
          quietMillis: 100,
          data: function (term, page) {
            return {q: term};
          },
          results: function (data, page) {
            return {results: data.results, more: false};
          }
        },
        allowClear: true
      });
      $("#s2id_admin-select a span").text("");
      $("input#admin-select").attr("value", "");

    });
  </script>
{% endblock %}

src/abilian/sbe/apps/social/templates/social/groups-new.html
{% extends "social/base.html" %}

{% from "social/macros.html" import render_field %}

{% block content %}
  <h2>{{ _("Create a new group") }}</h2>

  <form action="{{ request.path }}" method="POST" class="form-horizontal" id="edit-form">
    {{ form.csrf }}

    <fieldset>
      {%- for field in form %}
        {{ render_field(field) }}
      {%- endfor %}
    </fieldset>

    <div class="form-actions">
      {%- if for_new %}
        <button type="submit" class="btn btn-primary" name="_action" value="add">Add new</button>
        <button type="submit" class="btn cancel" name="_action" value="cancel">Cancel</button>
      {%- else %}
        <button type="submit" class="btn btn-primary" name="_action" value="save">Save changes</button>
        <button type="submit" class="btn cancel" name="_action" value="cancel">Cancel</button>
      {%- endif %}
    </div>

  </form>

  {%- if rules %}
    <script>
      $(document).ready(function () {
        var rules = {{ rules }};

        // Make bold labels for required fields
        $("label").each(function (i, e) {
          var for_ = $(e).attr("for");
          if (rules[for_] && rules[for_].required) {
            $(e).addClass("required");
          }
        });

        // Activate valitation plugin
        $("#edit-form").validate({
          /* debug: true, */
          rules: rules,
          highlight: function (label) {
            $(label).closest('.form-group').addClass('error');
          },
          unhighlight: function (label) {
            $(label).closest('.form-group').removeClass('error');
          },
        });
      });
    </script>
  {%- endif %}

{% endblock %}

src/abilian/sbe/apps/social/templates/social/groups.html
{% extends "social/base.html" %}

{% block content %}
  {% call m_box(_("Groups Directory")) %}

    {# don't change xml comment below for a jinja comment: it
   would remove the long message from i18n catalog... #}
    <!--      <p class="span7">
        {{ _("Create and join groups to discuss projects or to meet colleagues with similar skills, interests and hobbies. Public groups are open to anyone and appear in the groups directory. Private groups are invitation-only spaces for confidential activities, and do not appear in the groups directory.") }}
      </p>
-->
    {#
      {% if g.user.has_role("admin") %}
      <a class="btn btl-large btn-primary span2" style="width: 170px;"
              href="/social/groups/new">{{ _("Create new group") }}</a>
      {% endif %}
      #}

    <!-- TODO -->
    {#
    <ul class="nav nav-tabs">
      <li class="active"><a href="?tab=all_groups">{{ _("All public groups") }}</a></li>
      <li><a href="?tab=my_groups">{{ _("My groups") }}</a></li>
    </ul>
    #}

    <table class="grid">
      <thead>
      <tr>
        <th class="first" colspan="2">
          <a href="?sort_by=name">{{ _("Groups") }}</a>
        </th>

        <th class="">
          <a href="?sort_by=date_created">{{ _("Created On") }}</a>
        </th>

        <th class="">
          <a href="?sort_by=last_active">{{ _("Members") }}</a>
        </th>
        {#
        <th></th>
        #}
      </tr>
      </thead>

      <tbody>

      {% for group in groups %}
        <tr>
          <td class="picture">
            <a href="{{ url_for(".group_home", group_id=group.id) }}"><img
                class="avatar-45"
                src="{{ url_for(".group_mugshot", group_id=group.id, s=45) }}"></a>
          </td>

          <td class="identity">
            <div class="info">
              <a href="{{ url_for(".group_home", group_id=group.id) }}"><b>{{ group.name }}</b></a>

              <p>{{ group.description|default("", true) }}</p>
            </div>
          </td>

          <td>
            {{ group.created_at | date }}
          </td>

          <td>
            {{ group.members | count }}
          </td>

          {#
          <td>
            <form action="{{ group.url }}" method="post">
              <input type="hidden" name="return_url" value="{{ request.url }}">
              {% if not g.user.is_member_of(group) %}
              <button class="btn btn-primary" name="action" value="join">{{ _("Join") }}</button>
            {% else %}
              <button class="btn btn-danger" name="action" value="leave">{{ _("Leave") }}</button>
            {% endif %}
            </form>
          </td>
          #}
        </tr>
      {% endfor %}

      </tbody>
    </table>
  {% endcall %}

{% endblock %}

src/abilian/sbe/apps/social/templates/social/home.html
{% extends "social/base.html" %}
{% from "macros/box.html" import m_box %}
{% from "macros/activity.html" import m_activities %}

{% block content %}
  {% call m_box(_("Activity stream"), color="blue") %}
    {{ m_activities(activity_entries) }}
  {% endcall %}
{% endblock %}

{% block sidebar %}
  {% include "social/_sidebar.html" %}
{%- endblock %}

src/abilian/sbe/apps/social/templates/social/invite.html
{% extends "social/base.html" %}

{% block content %}
  <h2>{{ _("Invite colleagues to join this community") }}</h2>

  <p>
    {{ _("Please enter the email addresses of people you'd like to invite to the community. Enter one email address per line.") }}
  </p>

  <form action="/social/invite" method="POST" class="form-horizontal" id="edit-form">
    <fieldset>
      <div class="form-group">
        <label class="control-label" for="input-emails"><label for="emails">{{ _("Emails") }}</label></label>
        <div class="controls">
          <textarea id="emails" name="emails" cols="40" rows="10"></textarea>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label" for="input-message"><label
            for="message">{{ _("Personnalized message") }}</label></label>
        <div class="controls">
          <textarea id="message" name="message" cols="40" rows="10"></textarea>
        </div>
      </div>

    </fieldset>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary" name="action" value="invite">{{ _("Invite") }}</button>
      <button type="submit" class="btn cancel" name="action" value="cancel">{{ _("Cancel") }}</button>
    </div>

  </form>

{% endblock %}

src/abilian/sbe/apps/social/templates/social/widget_user_photo.html
{%- if user_id %}
  <img width="140" height="140" src="{{ user_photo_url(user_id, size=140) }}" class="media-object" alt=""/>
{%- endif %}

<input name="{{ field.name }}" type="file"
{%- for attr, val in attrs.items() %} {{ attr }}="{{ val }}"{%- endfor %}
/>